language: php
sudo: false

php:
  - "7.1"
  - "7.2"
  - "7.3"

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install --prefer-dist --no-interaction

script:
  - if [ $TRAVIS_PHP_VERSION = '7.2' ]; then vendor/bin/phpunit --coverage-clover build/logs/clover.xml; else vendor/bin/phpunit; fi
  - if [ $TRAVIS_PHP_VERSION = '7.2' ]; then vendor/bin/php-cs-fixer fix --config=vendor/ixocreate/coding-standard/.php_cs -v --dry-run --using-cache=no --path-mode=intersection `git diff --name-only --diff-filter=ACMRTUXB $TRAVIS_COMMIT_RANGE`; fi

after_success:
  - if [ $TRAVIS_PHP_VERSION = '7.2' ]; then php vendor/bin/php-coveralls -v; fi

notifications:
  email: false
  slack:
    secure: "awSbhN45ngPozjuf9IYRc95CZMvzsteN1peU6cojXGmmU/Qzd9xSWkzEon1WkW9DXn9qvwzk+UfBMS7K9G2SoNHPOZlS+rcaNKJ/9Ah/qn9egJINtZ7euUZBB6Nnf0QKe7B4JJ/n0yg/UqUJtiN1RGq25A+qaQpj5fmtbrfz6E5Oi6bySuosREh4bhraE74bzUlxGmdgRDQeRqet1z6mBt3daqYmOsI5YW/TcmTHGXKmD4B7cNRH+vbU7Heq89FY/ndqew0n8AtZo39weTUQnGJ1hDxJacI6FU6X266DlbJ46lCYgD9hxOG4Ji0ShxvCjAO7eRohoGSiUMdT8lKg/q6moBTXAzZLtM1objxVa9dCqA/a/ktko2WfrS7ZawBNpcGUQdbVhBzxSM0FnEWy0+p51BCf44gxKEMZlIxUC76L80FgipVXueawDKwdAPM0HdpiprmBjNINuzU91cdyScCRx3t+zwJdaeIJNLdNpjvltB0XMy3kMvmZtMyl4kC/OGkfGvmsMcqAzONJ8Sh+XXJac7lQQOoGg4c3qcK1glJnthLxa9aw8UfJouDXDlgUFo+FqdbjyKKgvgIojLisNMPqQRHUHQ9HljtTqdtEugeXMv04iOsqFOvA+/JuJZGFcNkpdtVxNDTsHgZmVXld9SEGfj0AEViOiL0TQygT5SU="
